<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrjoEdH\Shopware_Production_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrjoEdH/Shopware_Production_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrjoEdH.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrjoEdH\Shopware_Production_KernelDevDebugContainer::class, Shopware_Production_KernelDevDebugContainer::class, false);
}

return new \ContainerGrjoEdH\Shopware_Production_KernelDevDebugContainer([
    'container.build_hash' => 'GrjoEdH',
    'container.build_id' => '2440a9c2',
    'container.build_time' => 1625486821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrjoEdH');
